name: Auth-Reloaded
version: 1.0.0
main: auth.reloaded.AuthReloaded
author: TerThesz

commands:
  register:
    usage: /<command> <password> <confirm-password> [player]
    description: Register command
    aliases: [reg, r]
    permission: auth-reloaded.register
  login:
    usage: /<command> <password>
    description: Login command
    aliases: [log, l]
    permission: auth-reloaded.login
  register-other:
    usage: /<command> <player> <password> <confirm-password>
    description: Register another player
    aliases: [rego, ro, registerother]
    permission: auth-reloaded.register-other

# TODO: Try making dynamic permission error messages
# TODO: logout & unregister others

permissions:
  auth-reloaded.*:
    description: All auth-reloaded permissions
    default: false
    children:
      auth-reloaded.register: true
      auth-reloaded.login: true
      auth-reloaded.register-others: true
  auth-reloaded.register:
    description: Register command
    default: true
  auth-reloaded.login:
    description: Login command
    default: true
  auth-reloaded.register-other:
    description: Register others
    default: op